

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AnimalFarm.Core.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class AnimalFarmDbContext : DbContext
{
    public AnimalFarmDbContext()
        : base("name=AnimalFarmDbContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }


    public virtual ObjectResult<ProductView> GetProductViewsBySearchCriteria(string productCode, string productName, Nullable<int> categoryID)
    {

        var productCodeParameter = productCode != null ?
            new ObjectParameter("ProductCode", productCode) :
            new ObjectParameter("ProductCode", typeof(string));


        var productNameParameter = productName != null ?
            new ObjectParameter("ProductName", productName) :
            new ObjectParameter("ProductName", typeof(string));


        var categoryIDParameter = categoryID.HasValue ?
            new ObjectParameter("CategoryID", categoryID) :
            new ObjectParameter("CategoryID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductView>("GetProductViewsBySearchCriteria", productCodeParameter, productNameParameter, categoryIDParameter);
    }

}

}

