
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AnimalFarm.Core.Models
{

using System;
    
public partial class ProductView
{

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public int CategoryID { get; set; }

    public System.DateTime CreateDateTime { get; set; }

    public System.DateTime UpdateDateTime { get; set; }

    public string CategoryName { get; set; }

}

}
